Repository Miksus/rocketry, pull requests merged in 2022-07, with the labels that each got.

#25 Dev/session get repo
  docs/code/demos/advanced.py
  docs/code/demos/basic.py
  docs/code/demos/demo_basic.py
  docs/code/demos/intermediate.py
  docs/code/demos/minimal.py
  docs/code/minimal.py
  docs/examples/index.rst
  docs/index.rst
  docs/tutorial/quick_start.rst
  redengine/session.py
  redengine/test/session/test_core.py
Labels: enhancement

#27 Rename Return function argument in documentation
  docs/code/demos/intermediate.py
Labels: documentation

#43 Fix excessive CPU usage
  docs/tutorial/advanced.rst
  rocketry/session.py
  rocketry/test/conftest.py
  rocketry/test/session/test_config.py
Labels: bug

#46 Drop Pandas dependency
  docs/versions.rst
  requirements.txt
  requirements/ci.txt
  requirements/coverage.txt
  requirements/docs.txt
  rocketry/core/log/adapter.py
  rocketry/core/schedule.py
  rocketry/core/task.py
  rocketry/core/time/anchor.py
  rocketry/core/time/base.py
  rocketry/core/time/utils.py
  rocketry/pybox/query/base.py
  rocketry/pybox/time/__init__.py
  rocketry/pybox/time/convert.py
  rocketry/pybox/time/interval.py
  rocketry/session.py
  rocketry/test/condition/task/test_time.py
  rocketry/test/condition/task/test_time_executable.py
  rocketry/test/condition/task/test_time_optimized.py
  rocketry/test/helpers/log_helpers.py
  rocketry/test/pybox/query/test_query.py
  rocketry/test/pybox/test_convert.py
  rocketry/test/pybox/test_interval.py
  rocketry/test/schedule/process/test_core.py
  rocketry/test/schedule/test_core.py
  rocketry/test/schedule/test_failure.py
  rocketry/test/schedule/test_from_scripts.py
  rocketry/test/schedule/test_params.py
  rocketry/test/schedule/test_piping.py
  rocketry/test/schedule/test_terminate.py
  rocketry/test/schedule/test_traceback.py
  rocketry/test/session/test_logs.py
  rocketry/test/task/func/test_logging.py
  rocketry/test/task/func/test_run.py
  rocketry/test/task/func/test_run_delayed.py
  rocketry/test/time/delta/test_construct.py
  rocketry/test/time/delta/test_roll.py
  rocketry/test/time/interval/test_relative_day.py
  rocketry/test/time/interval/timeofday/test_roll.py
  rocketry/test/time/interval/timeofweek/test_core.py
  rocketry/test/time/logic/test_roll.py
  rocketry/test/time/test_contains.py
  rocketry/test/time/test_core.py
  rocketry/time/__init__.py
  rocketry/time/interval.py
  setup.py
Labels: core

#47 FIX: Minimal task
  rocketry/core/task.py
  rocketry/test/app/test_app.py
Labels: core

#48 fix: task param staging was not used
  rocketry/args/builtin.py
  rocketry/core/condition/base.py
  rocketry/core/parameters/arguments.py
  rocketry/core/parameters/parameters.py
  rocketry/core/task.py
Labels: core, built-in

#49 ENH: Add rocketry.args.TerminationFlag
  rocketry/args/__init__.py
  rocketry/args/builtin.py
  rocketry/core/task.py
  rocketry/test/schedule/test_params.py
Labels: built-in

#50 DOCS: Minor improvements
  docs/handbooks/config.rst
  docs/handbooks/index.rst
  docs/index.rst
  docs/tutorial/advanced.rst
  docs/tutorial/intermediate.rst
  scripts/systest/flask_api.py
  scripts/systest/load_test.py
  scripts/systest/pipelined.py
  scripts/systest/timing.py
Labels: documentation

#52 fix: FuncCond parametrizing
  docs/versions.rst
  rocketry/conditions/func.py
  rocketry/test/app/test_cond_api.py
Labels: bug, built-in

#53 Fix: task status discontinuity in restart
  docs/handbooks/index.rst
  docs/handbooks/logging.rst
  docs/index.rst
  docs/tutorial/intermediate.rst
  docs/versions.rst
  rocketry/core/task.py
  rocketry/test/task/func/test_logging.py
Labels: bug, documentation

#55 docs: fix minimal alternative with cond API
  docs/code/demos/minimal_with_api.py
  docs/index.rst
Labels: documentation

#60 ENH: Add async tasks
  rocketry/application.py
  rocketry/core/schedule.py
  rocketry/core/task.py
  rocketry/session.py
  rocketry/tasks/func.py
  rocketry/test/app/test_app.py
  rocketry/test/schedule/test_core.py
  rocketry/test/schedule/test_methods.py
  rocketry/test/schedule/test_terminate.py
  rocketry/test/session/test_construct.py
  rocketry/test/task/func/test_run.py
  rocketry/test/task/test_core.py
Labels: enhancement, core, built-in

#61 ENH: session shutdown
  rocketry/core/schedule.py
  rocketry/session.py
  rocketry/test/session/test_control.py
  rocketry/test/session/test_deprecate.py
Labels: enhancement, built-in

#57 ENH: Add new conditions to condition API
  docs/code/conds/api/scheduler.py
  docs/code/conds/api/task_running.py
  docs/code/conds/api/task_status.py
  docs/handbooks/conditions/api/index.rst
  docs/handbooks/conditions/api/logical.rst
  docs/handbooks/conditions/api/periodical.rst
  docs/handbooks/conditions/api/pipeline.rst
  docs/handbooks/conditions/api/scheduler.rst
  docs/handbooks/conditions/api/task_status.rst
  docs/handbooks/conditions/index.rst
  docs/handbooks/conditions/syntax/index.rst
  docs/handbooks/conditions/syntax/logical.rst
  docs/handbooks/conditions/syntax/periodical.rst
  docs/handbooks/conditions/syntax/pipeline.rst
  docs/handbooks/logging.rst
  rocketry/conditions/api.py
  rocketry/conditions/task/task.py
  rocketry/conds/__init__.py
  rocketry/core/task.py
  rocketry/test/condition/task/test_time.py
  rocketry/test/condition/task/test_time_optimized.py
  rocketry/test/condition/test_api.py
  rocketry/test/condition/test_parse.py
  rocketry/test/task/func/test_logging.py
  rocketry/test/task/test_core.py
  rocketry/test/time/delta/span/__init__.py
  rocketry/test/time/delta/span/test_construct.py
  rocketry/test/time/delta/span/test_contains.py
  rocketry/test/time/delta/span/test_roll.py
  rocketry/time/__init__.py
  rocketry/time/delta.py
Labels: built-in

#62 fix: Task to JSON
  rocketry/args/builtin.py
  rocketry/core/parameters/parameters.py
  rocketry/core/task.py
  rocketry/test/task/test_core.py
Labels: bug, core

#56 fix: support for nested parameters and FuncParam reference
  docs/handbooks/config.rst
  rocketry/args/builtin.py
  rocketry/args/secret.py
  rocketry/core/parameters/parameters.py
  rocketry/core/task.py
  rocketry/parameters/func.py
  rocketry/session.py
  rocketry/tasks/command.py
  rocketry/test/app/test_app.py
  rocketry/test/session/params/test_func.py
Labels: core, built-in

#63 Docs/update
  README.md
  docs/code/demos/fast_api/api.py
  docs/code/demos/fast_api/main.py
  docs/code/demos/fast_api/scheduler.py
  docs/code/demos/minimal_async.py
  docs/code/execution.py
  docs/examples/demos/fastapi.rst
  docs/examples/index.rst
  docs/handbooks/config.rst
  docs/handbooks/index.rst
  docs/handbooks/task/execution.rst
  docs/handbooks/task/index.rst
  docs/handbooks/task/parameterization.rst
  docs/handbooks/task/termination.rst
  docs/index.rst
  docs/tutorial/basic.rst
  docs/tutorial/intermediate.rst
  rocketry/test/app/test_app.py
  rocketry/test/session/params/test_func.py
Labels: documentation

#64 docs: update version
  docs/versions.rst
Labels: documentation

#65 test: fix name error on windows
  rocketry/test/session/params/test_func.py
Labels: bug, test
