Repository Miksus/rocketry, pull requests merged in 2022-11, with the labels that each got.

#136 Fix task deletion bug #130
  rocketry/session.py
  rocketry/test/app/test_app.py
Labels: bug

#152 ENH: Update settings
  docs/code/demos/fast_api/scheduler.py
  docs/code/demos/minimal_async.py
  docs/cookbook/django.rst
  docs/cookbook/fastapi.rst
  docs/handbooks/config.rst
  docs/handbooks/task/execution.rst
  docs/tutorial/basic.rst
  docs/versions.rst
  rocketry/__init__.py
  rocketry/application.py
  rocketry/core/schedule.py
  rocketry/core/task.py
  rocketry/session.py
  rocketry/test/app/test_app.py
  rocketry/test/app/test_cond_api.py
  rocketry/test/app/test_custom.py
  rocketry/test/app/test_grouper.py
  rocketry/test/conftest.py
  rocketry/test/schedule/test_core.py
  rocketry/test/schedule/test_terminate.py
  rocketry/test/session/test_config.py
  rocketry/test/session/test_construct.py
  rocketry/test/session/test_core.py
  rocketry/test/session/test_deprecate.py
  rocketry/test/task/func/test_construct.py
  rocketry/test/task/test_core.py
Labels: enhancement, core

#154 DOCS: Minor documentation improvement
  Contributors.md
  docs/_static/css/code.css
  docs/conf.py
  docs/contributing.rst
  docs/handbooks/task/index.rst
  docs/handbooks/task/observer.rst
  docs/handbooks/task/termination.rst
Labels: documentation

#140 ENH: App config
  docs/cookbook/bigger_applications.rst
  docs/cookbook/index.rst
  docs/cookbook/settings.rst
  docs/tutorial/intermediate.rst
  rocketry/application.py
  rocketry/args/__init__.py
  rocketry/args/builtin.py
  rocketry/conditions/api.py
  rocketry/conditions/task/task.py
  rocketry/conditions/task/utils.py
  rocketry/conds/__init__.py
  rocketry/core/hook.py
  rocketry/core/log/adapter.py
  rocketry/core/parameters/parameters.py
  rocketry/core/schedule.py
  rocketry/core/task.py
  rocketry/test/app/test_custom.py
  rocketry/test/app/test_hooks.py
  rocketry/test/args/test_args.py
  rocketry/test/test_hooks.py
Labels: documentation, built-in

#147 ENH: Optional Timezone
  docs/cookbook/testing.rst
  docs/handbooks/config.rst
  docs/versions.rst
  requirements/coverage.txt
  rocketry/conditions/api.py
  rocketry/conditions/meta.py
  rocketry/conditions/scheduler.py
  rocketry/conditions/task/task.py
  rocketry/conditions/task/utils.py
  rocketry/conditions/time.py
  rocketry/core/log/adapter.py
  rocketry/core/schedule.py
  rocketry/core/task.py
  rocketry/core/time/base.py
  rocketry/core/time/utils.py
  rocketry/log/log_record.py
  rocketry/pybox/time/convert.py
  rocketry/session.py
  rocketry/test/condition/task/test_time_executable.py
  rocketry/test/condition/task/test_time_optimized.py
  rocketry/test/condition/task/test_time_runnable.py
  rocketry/test/condition/test_timezone.py
  rocketry/test/schedule/test_core.py
  rocketry/test/session/test_logs.py
  rocketry/test/task/test_core.py
  rocketry/test/task/test_pickle.py
  rocketry/test/time/delta/span/test_contains.py
  rocketry/test/time/delta/test_contains.py
  rocketry/test/time/test_contains.py
  rocketry/time/delta.py
Labels: enhancement, core

#155 BUG: Cache before startup
  docs/cookbook/settings.rst
  docs/versions.rst
  rocketry/core/schedule.py
  rocketry/core/task.py
  rocketry/test/app/test_hooks.py
  rocketry/test/session/test_logs.py
  rocketry/test/task/func/test_logging.py
  rocketry/test/task/test_core.py
Labels: bug

#156 ENH: Add SchedulerLogger
  docs/versions.rst
  rocketry/args/__init__.py
  rocketry/args/builtin.py
  rocketry/test/args/test_args.py
Labels: enhancement

#160 BUG: Fix multilaunch spam
  rocketry/core/schedule.py
  rocketry/core/task.py
  rocketry/test/schedule/test_multilaunch.py
Labels: bug
