Repository Miksus/rocketry, pull requests merged in 2022-09, with the labels that each got.

#83 ENH: Option to silence log errors
  docs/handbooks/config.rst
  requirements/build.txt
  requirements/ci.txt
  requirements/coverage.txt
  rocketry/core/schedule.py
  rocketry/core/task.py
  rocketry/exc.py
  rocketry/session.py
  rocketry/test/condition/task/test_time.py
  rocketry/test/condition/task/test_time_executable.py
  rocketry/test/condition/task/test_time_runnable.py
  rocketry/test/conftest.py
  rocketry/test/helpers/log_helpers.py
  rocketry/test/helpers/task_helpers.py
  rocketry/test/schedule/test_core.py
  rocketry/test/schedule/test_failure.py
  rocketry/test/session/test_construct.py
  rocketry/test/session/test_deprecate.py
  rocketry/test/session/test_logs.py
  rocketry/test/task/func/test_logging.py
  rocketry/test/task/func/test_run.py
  rocketry/test/task/func/test_run_delayed.py
  rocketry/test/task/test_core.py
  rocketry/test/test_testing.py
  rocketry/testing/__init__.py
  rocketry/testing/log.py
Labels: enhancement, core

#87 ENH: add never timeperiod
  rocketry/core/time/__init__.py
  rocketry/core/time/base.py
  rocketry/test/time/test_static.py
  rocketry/time/__init__.py
Labels: built-in

#90 FIX: Async/threaded tasks limit max_process_count
  rocketry/core/schedule.py
  rocketry/core/task.py
  rocketry/test/schedule/process/test_core.py
Labels: bug, core

#84 ENH: Add crontime
  docs/code/conds/api/crontime.py
  docs/code/conds/api/crontime_kwargs.py
  docs/handbooks/conditions/api/cron.rst
  rocketry/conditions/api.py
  rocketry/conds/__init__.py
  rocketry/test/condition/test_api.py
Labels: enhancement, built-in

#91 FIX: TimeOfMinute subseconds
  rocketry/core/time/anchor.py
  rocketry/test/time/interval/test_construct.py
  rocketry/test/time/interval/test_contains.py
  rocketry/test/time/interval/test_roll.py
  rocketry/test/time/interval/timeofday/__init__.py
  rocketry/test/time/interval/timeofday/test_contains.py
  rocketry/test/time/interval/timeofweek/test_contains.py
  rocketry/test/time/interval/timeofweek/test_core.py
  rocketry/time/interval.py
Labels: bug, built-in

#92 ENH: Add TimeOfSecond and secondly
  rocketry/conditions/api.py
  rocketry/conds/__init__.py
  rocketry/core/time/anchor.py
  rocketry/parse/_setup_cond_parsers.py
  rocketry/test/condition/test_api.py
  rocketry/test/condition/test_parse.py
  rocketry/test/time/interval/test_construct.py
  rocketry/test/time/interval/test_contains.py
  rocketry/time/interval.py
Labels: enhancement, built-in

#94 ENH: Pass arguments to FuncCond
  docs/tutorial/intermediate.rst
  rocketry/conditions/func.py
  rocketry/test/app/test_custom.py
  rocketry/test/condition/test_create.py
Labels: enhancement, built-in

#98 TEST: Increase coverage
  rocketry/application.py
  rocketry/args/__init__.py
  rocketry/conditions/scheduler.py
  rocketry/conditions/task/task.py
  rocketry/conditions/task/utils.py
  rocketry/conditions/time.py
  rocketry/core/condition/base.py
  rocketry/core/hook.py
  rocketry/core/log/adapter.py
  rocketry/core/meta.py
  rocketry/core/schedule.py
  rocketry/core/task.py
  rocketry/core/time/anchor.py
  rocketry/core/time/base.py
  rocketry/core/time/utils.py
  rocketry/pybox/string/parse/closure.py
  rocketry/pybox/time/__init__.py
  rocketry/pybox/time/convert.py
  rocketry/tasks/func.py
  rocketry/test/app/test_app.py
  rocketry/test/app/test_deprecated.py
  rocketry/test/args/__init__.py
  rocketry/test/args/test_core.py
  rocketry/test/args/test_misc.py
  rocketry/test/condition/test_core.py
  rocketry/test/condition/test_parse_clause.py
  rocketry/test/condition/test_scheduler.py
  rocketry/test/conftest.py
  rocketry/test/parameters/test_params.py
  rocketry/test/pybox/test_convert.py
  rocketry/test/pytest.ini
  rocketry/test/schedule/test_core.py
  rocketry/test/schedule/test_params.py
  rocketry/test/schedule/test_terminate.py
  rocketry/test/schedule/test_traceback.py
  rocketry/test/session/test_construct.py
  rocketry/test/session/test_run.py
  rocketry/test/session/test_utils.py
  rocketry/test/task/func/test_logging.py
  rocketry/test/test_adapter.py
  rocketry/test/time/interval/test_construct.py
  rocketry/test/time/test_core.py
  rocketry/test/time/test_parse.py
  rocketry/test/time/test_static.py
  rocketry/time/interval.py
  rocketry/utils/dependencies.py
Labels: test

#85 ENH: retry condition
  rocketry/conditions/api.py
  rocketry/conditions/task/task.py
  rocketry/conds/__init__.py
  rocketry/test/condition/task/test_retry.py
  rocketry/test/condition/test_api.py
Labels: enhancement, built-in

#101 Dev/force run params
  docs/code/demos/fast_api/api.py
  docs/handbooks/arguments.rst
  docs/handbooks/index.rst
  docs/handbooks/parameterization.rst
  docs/handbooks/task/index.rst
  docs/handbooks/task/parameterization.rst
  rocketry/args/__init__.py
  rocketry/args/builtin.py
  rocketry/core/parameters/arguments.py
  rocketry/core/parameters/parameters.py
  rocketry/core/task.py
  rocketry/tasks/func.py
  rocketry/test/args/test_args.py
  rocketry/test/args/test_core.py
  rocketry/test/args/test_misc.py
  rocketry/test/schedule/test_core.py
  rocketry/test/session/params/test_func.py
  rocketry/test/session/params/test_params.py
  rocketry/test/session/params/test_params_order.py
  rocketry/test/session/params/test_return.py
  rocketry/test/session/test_control_task.py
  rocketry/test/task/test_core.py
Labels: bug, enhancement, core

#96 REF: Change default task_execution to async
  docs/handbooks/config.rst
  rocketry/session.py
  rocketry/test/session/test_deprecate.py
Labels: core

#95 BUG: execution not released if cycle_sleep=None
  rocketry/core/schedule.py
  rocketry/test/schedule/test_core.py
Labels: bug, core

#102 DOCS: Upgrade
  README.md
  docs/_static/logo.png
  docs/code/conds/api/pipe_multiple.py
  docs/code/demos/intermediate.py
  docs/conf.py
  docs/contributing.rst
  docs/cookbook/conditions.rst
  docs/cookbook/controlling_runtime.rst
  docs/cookbook/index.rst
  docs/cookbook/robust_applications.rst
  docs/cookbook/testing.rst
  docs/header.html
  docs/index.rst
  docs/rocketry_vs_alternatives.rst
  docs/versions.rst
  requirements/docs.txt
Labels: documentation

#103 FIX: Test warnings
  rocketry/test/schedule/test_core.py
  rocketry/test/session/test_config.py
  rocketry/test/session/test_construct.py
Labels: test

#68 add: Custom arguments with custom cond
  rocketry/conditions/func.py
  rocketry/test/app/test_cond_api.py
Labels: built-in

#104 BUG: timeperiod at end
  docs/versions.rst
  rocketry/core/task.py
  rocketry/core/time/anchor.py
  rocketry/test/condition/test_api.py
  rocketry/test/task/func/test_run.py
  rocketry/test/time/interval/test_construct.py
Labels: bug

#105 DOCS: Minor update
  docs/code/snippets/custom_condition.py
  docs/code/snippets/parallelization.py
  docs/code/snippets/parametrize.py
  docs/code/snippets/pipeline.py
  docs/cookbook/conditions.rst
  docs/handbooks/arguments.rst
  docs/how_it_works.rst
  docs/index.rst
  docs/versions.rst
Labels: documentation

#106 ENH: Add scheduler_cycles
  docs/code/conds/api/scheduler_cycles.py
  docs/code/conds/api/scheduler_running.py
  docs/handbooks/conditions/api/scheduler.rst
  docs/versions.rst
  rocketry/conditions/api.py
  rocketry/conditions/scheduler.py
  rocketry/conds/__init__.py
  rocketry/test/condition/test_api.py
Labels: enhancement

#110 Fix: wrong class name reference in docs
  docs/handbooks/logging.rst
Labels: documentation

#116 FIX: Hotfix for the warnings due to task_execution
  .github/workflows/main.yml
  rocketry/__init__.py
  rocketry/application.py
  rocketry/core/schedule.py
  rocketry/core/task.py
  rocketry/session.py
  rocketry/test/app/test_app.py
  rocketry/test/app/test_deprecated.py
  rocketry/test/app/test_grouper.py
  rocketry/test/args/test_args.py
  rocketry/test/condition/task/test_basic.py
  rocketry/test/conftest.py
  rocketry/test/schedule/test_core.py
  rocketry/test/schedule/test_params.py
  rocketry/test/session/test_core.py
  rocketry/test/session/test_logs.py
  rocketry/test/session/test_utils.py
  rocketry/test/task/command/test_construct.py
  rocketry/test/task/func/test_construct.py
  rocketry/test/task/func/test_export.py
  rocketry/test/task/func/test_logging.py
  rocketry/test/task/func/test_run_delayed.py
  rocketry/test/task/misc/test_restart.py
  rocketry/test/task/test_pickle.py
  rocketry/test/test_adapter.py
  rocketry/test/test_hooks.py
Labels: bug

#118 docs: updated version according to 2.4.1
  docs/versions.rst
Labels: documentation

#119 TEST: fix warnings in tests
  .github/workflows/main.yml
  rocketry/session.py
  rocketry/test/session/params/test_return.py
  rocketry/test/session/test_logs.py
  rocketry/test/task/code/test_construct.py
  rocketry/test/task/func/test_run.py
  rocketry/test/task/misc/test_restart.py
  rocketry/test/task/misc/test_shutdown.py
Labels: test
