Repository Miksus/rocketry, pull requests merged in 2022-08, with the labels that each got.

#67 fix typo in docs/index.rst
  docs/index.rst
Labels: documentation

#73 ENH: Add cron scheduler
  docs/code/conds/api/cron.py
  docs/code/conds/api/cron_kwargs.py
  docs/handbooks/conditions/api/cron.rst
  docs/handbooks/conditions/api/index.rst
  docs/index.rst
  docs/versions.rst
  rocketry/conditions/api.py
  rocketry/conditions/task/task.py
  rocketry/conds/__init__.py
  rocketry/core/time/__init__.py
  rocketry/core/time/anchor.py
  rocketry/core/time/base.py
  rocketry/core/time/utils.py
  rocketry/parse/_setup_cond_parsers.py
  rocketry/parse/time.py
  rocketry/pybox/time/__init__.py
  rocketry/pybox/time/convert.py
  rocketry/pybox/time/interval.py
  rocketry/test/condition/task/test_time_executable.py
  rocketry/test/condition/task/test_time_runnable.py
  rocketry/test/condition/test_api.py
  rocketry/test/condition/test_parse.py
  rocketry/test/pybox/test_interval.py
  rocketry/test/time/delta/span/test_contains.py
  rocketry/test/time/delta/test_contains.py
  rocketry/test/time/interval/test_construct.py
  rocketry/test/time/interval/timeofday/test_contains.py
  rocketry/test/time/interval/timeofday/test_roll.py
  rocketry/test/time/interval/timeofweek/test_contains.py
  rocketry/test/time/interval/timeofweek/test_core.py
  rocketry/test/time/logic/test_construct.py
  rocketry/test/time/logic/test_in.py
  rocketry/test/time/logic/test_roll.py
  rocketry/test/time/test_contains.py
  rocketry/test/time/test_core.py
  rocketry/test/time/test_cron.py
  rocketry/test/time/test_parse.py
  rocketry/test/time/test_skip.py
  rocketry/test/time/test_static.py
  rocketry/time/__init__.py
  rocketry/time/cron.py
  rocketry/time/delta.py
  rocketry/time/interval.py
Labels: enhancement, core, built-in

#79 ENH: Update session
  docs/versions.rst
  rocketry/__init__.py
  rocketry/application.py
  rocketry/core/schedule.py
  rocketry/core/task.py
  rocketry/session.py
  rocketry/test/app/test_app.py
  rocketry/test/app/test_grouper.py
  rocketry/test/condition/task/test_basic.py
  rocketry/test/condition/task/test_compare.py
  rocketry/test/condition/task/test_time.py
  rocketry/test/condition/task/test_time_executable.py
  rocketry/test/condition/task/test_time_optimized.py
  rocketry/test/condition/task/test_time_runnable.py
  rocketry/test/condition/test_meta.py
  rocketry/test/schedule/process/test_core.py
  rocketry/test/schedule/test_conditions.py
  rocketry/test/schedule/test_core.py
  rocketry/test/schedule/test_failure.py
  rocketry/test/schedule/test_from_scripts.py
  rocketry/test/schedule/test_piping.py
  rocketry/test/schedule/test_scheduler_conditions.py
  rocketry/test/schedule/test_terminate.py
  rocketry/test/schedule/test_traceback.py
  rocketry/test/session/params/test_func.py
  rocketry/test/session/params/test_params.py
  rocketry/test/session/params/test_return.py
  rocketry/test/session/test_core.py
  rocketry/test/session/test_run.py
  rocketry/test/session/test_utils.py
  rocketry/test/task/code/test_construct.py
  rocketry/test/task/command/test_run.py
  rocketry/test/task/func/test_construct.py
  rocketry/test/task/func/test_logging.py
  rocketry/test/task/func/test_run.py
  rocketry/test/task/func/test_run_delayed.py
  rocketry/test/task/misc/test_restart.py
  rocketry/test/task/misc/test_shutdown.py
  rocketry/test/task/test_core.py
  rocketry/test/task/test_pickle.py
  rocketry/test/test_hooks.py
  rocketry/utils/dependencies.py
Labels: enhancement, core

#74 DOCS: Update documentation
  docs/conf.py
  docs/cookbook/bigger_applications.rst
  docs/cookbook/fastapi.rst
  docs/cookbook/index.rst
  docs/examples/demos/fastapi.rst
  docs/examples/index.rst
  docs/handbooks/conditions/classes.rst
  docs/handbooks/conditions/classes/index.rst
  docs/handbooks/conditions/index.rst
  docs/handbooks/index.rst
  docs/handbooks/logging.rst
  docs/handbooks/structure.rst
  docs/index.rst
  docs/rocketry_vs_alternatives.rst
  docs/tutorial/advanced.rst
  docs/tutorial/intermediate.rst
Labels: documentation

#81 ENH: Add AT to hourly, daily, weekly etc.
  docs/code/conds/api/periodical_restricted.py
  docs/handbooks/conditions/api/periodical.rst
  rocketry/conditions/api.py
  rocketry/test/condition/test_api.py
Labels: built-in
